services:
    server:
        build:
            context: .
            target: dev
        depends_on:
            - database
        ports:
            - '${APP_PORT}:${APP_PORT}'
        environment:
          - "DB_HOST=${DB_HOST}"
          - "DB_USER=${DB_USER}"
          - "DB_PASS=${DB_PASS}"
          - "DB_NAME=${DB_NAME}"
          - "DB_PORT=${DB_PORT}"
          - "APP_PORT=${APP_PORT}"
          - "JWT_SECRET=${JWT_SECRET}"
          - "CACHE_SERVER=${CACHE_SERVER}"

    database:
        image: postgres:15
        restart: always
        environment:
          - "POSTGRES_USER=${DB_USER}"
          - "POSTGRES_PASSWORD=${DB_PASS}"
          - "POSTGRES_DB=${DB_NAME}"
        ports:
          - "${DB_PORT}:$dbPort"
        volumes: 
          - dbdata:/var/lib/postgresql/data
          - ./migrations:/migrations

    cache:
        image: memcached:1.6
        restart: always

volumes:
  dbdata:
